### ISSUE TITLE
Impossible to compile

### ISSUE THREAD

**Issue by lauhub** [SingularityT3/PseudoEngine2#2]
Hi,

I tried to compile as indicated on both macOS Mojave (10.14) and Debian Bullseye (11).

I got error.

macOS

```
$ cmake -B build 
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/ccache - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/ccache - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user1/PseudoEngine2/build
$ cmake --build build --config Release
[  1%] Building CXX object CMakeFiles/PseudoEngine2.dir/cmake_pch.hxx.pch
In file included from <built-in>:1:
In file included from /Users/user1/PseudoEngine2/build/CMakeFiles/PseudoEngine2.dir/cmake_pch.hxx:5:
/Users/user1/PseudoEngine2/src/pch.h:11:10: fatal error: 'concepts' file not found
#include <concepts>
         ^~~~~~~~~~
1 error generated.
gmake[2]: *** [CMakeFiles/PseudoEngine2.dir/build.make:77: CMakeFiles/PseudoEngine2.dir/cmake_pch.hxx.pch] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/PseudoEngine2.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

Debian:

```
$ cmake -B build -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/laurent/PseudoEngine2/build
laurent@debian-graphique-demo:~/PseudoEngine2$ cmake --build build --config Release
Scanning dependencies of target PseudoEngine2
[  1%] Building CXX object CMakeFiles/PseudoEngine2.dir/cmake_pch.hxx.gch
[  3%] Building CXX object CMakeFiles/PseudoEngine2.dir/src/lexer/symbolLexer.cpp.o
In file included from /home/laurent/PseudoEngine2/src/psc/types/types.h:7,
                 from /home/laurent/PseudoEngine2/src/psc/variable.h:5,
                 from /home/laurent/PseudoEngine2/src/psc/scope/context.h:6,
                 from /home/laurent/PseudoEngine2/src/psc/error.h:5,
                 from /home/laurent/PseudoEngine2/src/lexer/lexer.h:6,
                 from /home/laurent/PseudoEngine2/src/lexer/symbolLexer.cpp:4:
/home/laurent/PseudoEngine2/src/psc/types/datatypes.h:10:15: error: expected nested-name-specifier before ‘enum’
   10 |         using enum Type;
      |               ^~~~
In file included from /home/laurent/PseudoEngine2/src/psc/variable.h:5,
                 from /home/laurent/PseudoEngine2/src/psc/scope/context.h:6,
                 from /home/laurent/PseudoEngine2/src/psc/error.h:5,
                 from /home/laurent/PseudoEngine2/src/lexer/lexer.h:6,
                 from /home/laurent/PseudoEngine2/src/lexer/symbolLexer.cpp:4:
/home/laurent/PseudoEngine2/src/psc/types/types.h:217:22: error: ‘year_month_day’ in namespace ‘std::chrono’ does not name a type
  217 |         std::chrono::year_month_day date;
      |                      ^~~~~~~~~~~~~~
/home/laurent/PseudoEngine2/src/psc/types/types.h:221:41: error: expected ‘)’ before ‘date’
  221 |         Date(std::chrono::year_month_day date);
      |             ~                           ^~~~~
      |                                         )
In file included from /home/laurent/PseudoEngine2/src/psc/scope/context.h:7,
                 from /home/laurent/PseudoEngine2/src/psc/error.h:5,
                 from /home/laurent/PseudoEngine2/src/lexer/lexer.h:6,
                 from /home/laurent/PseudoEngine2/src/lexer/symbolLexer.cpp:4:
/home/laurent/PseudoEngine2/src/psc/array.h:48:2: warning: extra ‘;’ [-Wpedantic]
   48 | };
      |  ^
In file included from /home/laurent/PseudoEngine2/src/psc/scope/context.h:8,
                 from /home/laurent/PseudoEngine2/src/psc/error.h:5,
                 from /home/laurent/PseudoEngine2/src/lexer/lexer.h:6,
                 from /home/laurent/PseudoEngine2/src/lexer/symbolLexer.cpp:4:
/home/laurent/PseudoEngine2/src/psc/procedure.h:54:2: warning: extra ‘;’ [-Wpedantic]
   54 | };
      |  ^
gmake[2]: *** [CMakeFiles/PseudoEngine2.dir/build.make:98 : CMakeFiles/PseudoEngine2.dir/src/lexer/symbolLexer.cpp.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:95 : CMakeFiles/PseudoEngine2.dir/all] Erreur 2
gmake: *** [Makefile:160 : all] Erreur 2
```

What are the dependecies/libraries to be installed before compiling ?

**Comment by SingularityT3** [comment]
Please use a more recent version of gcc, it compiles fine on any version above 11.3.0 as far as I've tested.

**Comment by SingularityT3** [comment]
Closing due to inactivity
